// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jxrqynnbgitlsjtuljxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4cnF5bm5iZ2l0bHNqdHVsanh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjExMzgsImV4cCI6MjA3MzQzNzEzOH0.snACOt83q8LIxXtdwsZWEPAypLkAEKQDYqjAULd4fuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);